### ISSUE TITLE
Could you add a referer in the request header?

### ISSUE THREAD

**Issue by Jovany-Rong** [frospirum/arkhelper#1]
Hi,

I'm the author of ArkStory. Could you add a referer in the request header so that the administrators of ArkStory or other websites are able to identify the source of the requests? If not, could you make some special remarks in user agent?

By the way, the address of ArkStory has been changed to **https://arkstory.cc**.

Best regards!

**Comment by frospirum** [comment]
I changed user-agent to `Mozilla/5.0 (Linux; Android; Mobile) Arkhelper/0.4.8`. Is this change useful to you? 

p.s. Actually, there is no need to use English (laugh

**Comment by Jovany-Rong** [comment]
哈哈哈，感谢，帮大忙啦。

**Comment by Jovany-Rong** [comment]
我目前用的百度统计，貌似没有自定义UA的统计功能，这个我后面自己做个统计功能，如果没有生效的话我再在此Issue回复您。

**Comment by Jovany-Rong** [comment]
啊，如果不行的话我再新开一个Issue好了，感谢大佬！

**Comment by frospirum** [comment]
这个issue暂时不会关的。
主要是有些好奇您要求自定义ua的用途，我开始还以为是要用UA统计各渠道的访问量，不过现在看来好像并不是

**Comment by Jovany-Rong** [comment]
是这个需求没错，只不过目前百度统计貌似只能通过referer来判断来源（例如NGA等），而不能使用UA来统计。所以我感觉这个可能得后端来做这个统计，当然，也可能是我孤陋寡闻了，如果您知道有什么方便的工具，可以推荐给我，不胜感激。

**Comment by frospirum** [comment]
这样啊，相关的东西我不太懂，没法给您提供什么帮助。另外新UA后面的版本号是会变的，如果对您的统计有什么影响的话请及时告知。

**Comment by Jovany-Rong** [comment]
好的，非常感谢！
